figure('name', 'Spectrogram', 'Position',[100 100 1000 500]); 
tiledlayout(2,1);
nexttile %Spectrogram
image([0 HighestIndex], [0 1*10^6], FFTMat);
title('Spectrogram');
cb = colorbar;
title(cb,'        Intensity')
xlabel('Waveform no.');
ylabel('Frequency [kHz]');
annotation('textbox', [0.8 0.87 0.8 0.1], ...
    'String', append('Total hits:', num2str(HighestIndex)), ...
    'Color', [1 0 0], ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none')

nexttile %High amplitude filter
image([0 HighestIndex], [0 0], BinFFT);
title(append('HAF (',num2str(HAFfilter),')'));
xlabel('Waveform no.');
annotation('textbox', [0.79 0.393 0.8 0.1], ...
    'String', append('Filtered hits:', num2str(K)), ...
    'Color', [1 0 0], ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none')